core/urls.py

from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('invoice.urls')),

    path('accounts/', include('allauth.urls')),

    ] 
    
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

invoice/urls.py
from django.urls import include, path
from . import views

app_name = 'invoice'

urlpatterns = [
    path('', views.index, name="index"),
    path('update/', views.AccountItemUpdateView.as_view(), name="update"),
    path('invoice_list/', views.RevenueListView.as_view(), name="invoice-list"),
    path('pdf_preview/<str:slug>', views.PdfCreateDetailView.as_view(), name="pdf-preview"),
    path('pdf_create/<str:slug>', views.pdfcreate, name="pdf-create"),

    path('csv_create/', views.CSVListView.as_view(), name="csv-create"),

    ### BACKUP ROUTE
    # URL for the home page (optional)
    path('backup/', views.backup_home_view, name='backup_home'),

    # URL to trigger the local backup
    path('backup/local/', views.local_db_backup_view, name='local_db_backup'),

    # URL to trigger the NAS copy (copies the latest local backup)
    path('backup/nas/', views.nas_db_backup_view, name='nas_db_backup'),

    # POSTGRES
    path('postgres_backup/', views.postgres_db_backup_to_nas_as_json, name='postgres-backup'),
    path('restore/', views.restore_view, name='restore-db'),

    # added 2025/12/25 for UPDATE upon logoff
    path('logout-backup/', views.logout_and_backup_view, name='logout_backup'),
]

invoice/forms.py
from django import forms
from .models import BankAccount, Company, AccountItem, InvoiceCode
from django.forms import modelformset_factory


"""
計上する項目を入力する
"""

class AccountItemForm(forms.ModelForm):
    DELETE = forms.BooleanField(required=False, widget=forms.HiddenInput) 
    
    class Meta:
        model = AccountItem
        fields = '__all__'
        widgets = {
            'invoice_bt': forms.TextInput(attrs={

                'class': 'form-control',
                'oninput': 'formatWithCommas(this)',
                'style': 'text-align: right;',
            }),
            'invoice_tax': forms.TextInput(attrs={
                'class': 'form-control',
                'oninput': 'formatWithCommas(this)',
                'style': 'text-align: right;',
            }),
            'invoice_at': forms.TextInput(attrs={
                'class': 'form-control',
                'oninput': 'formatWithCommas(this)',
                'style': 'text-align: right;',
            }),
        }

AccountItemFormSet = modelformset_factory(AccountItem, form=AccountItemForm, fields='__all__', extra=1, can_delete=True)

"""
請求書コードを修正
"""

class InvoiceCodeForm(forms.ModelForm):
    DELETE = forms.BooleanField(required=False, widget=forms.HiddenInput) 
    
    class Meta:
        model = InvoiceCode
        fields = '__all__'
        widgets = {
            'invoice_bt_ttl': forms.TextInput(attrs={

                'class': 'form-control',
                'oninput': 'formatWithCommas(this)',
                'style': 'text-align: right;',
            }),
            'invoice_tax_ttl': forms.TextInput(attrs={
                'class': 'form-control',
                'oninput': 'formatWithCommas(this)',
                'style': 'text-align: right;',
            }),
            'invoice_at_ttl': forms.TextInput(attrs={
                'class': 'form-control',
                'oninput': 'formatWithCommas(this)',
                'style': 'text-align: right;',
            }),
        }

InvoiceCodeFormSet = modelformset_factory(InvoiceCode, form=InvoiceCodeForm, fields='__all__', extra=1, can_delete=True)

invoice/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.views.generic import View, ListView, DetailView
from django.urls import reverse_lazy, reverse
from .models import AccountItem, Company, InvoiceCode, CsvDate
from . import calc
from .calc import strip_date
from .forms import AccountItemFormSet
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
from datetime import datetime
import os, subprocess
from .  import backup_logic
from django.contrib.auth import logout

# Create your views here.
@login_required
def index(request):
    calc.set_invoice_code()
    calc.invoice_code_slug_save()
    calc.total_amount_calc()
    return render(request, 'invoice/index.html')


"""
Account Item Update
"""
class AccountItemUpdateView(LoginRequiredMixin, View):
    template_name = 'invoice/account_item_input.html'

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        return render(request, self.template_name, context)

    def get_context_data(self, **kwargs):
        context = {}
        selected_company = self.request.GET.get('company')
        if selected_company == "" or selected_company is None:
            selected_company = ""
        print("selected_company 101", selected_company)
        print("passing 101")
        selected_month = self.request.GET.get('month') if self.request.GET.get('month') else timezone.now().strftime('%Y-%m-%d')
        _, start_month, end_of_month = strip_date(selected_month)

        if selected_company == "" or selected_company is None:
            print("passing 102")
            queryset = AccountItem.objects.filter(
                invoice_date__gte=start_month,
                invoice_date__lte=end_of_month,
                ).order_by('-item_code__slug', 'invoice_date')
        else:
            print("passing 103")
            queryset = AccountItem.objects.filter(
                company=Company.objects.get(id=selected_company),
                invoice_date__gte=start_month,
                invoice_date__lte=end_of_month,
                ).order_by('-item_code__slug', 'invoice_date')
        
        formset = AccountItemFormSet(queryset=queryset)
        context['companies'] = Company.objects.all()  # Assuming Bukken is your model name
        context['selected_company'] = selected_company  # Selected bukken value
        context['selected_month'] = selected_month  # Selected month value
        context['formset'] = formset  # Formset for the selected month

        return context
    
    def post(self, request, *args, **kwargs):
        
        selected_company = request.POST.get('company', None)
        selected_month = request.POST.get('month', None) 
        if selected_company == "":
            selected_company = ""  # Treat as no filter for company (all companies)
        url = reverse('invoice:update')  # This gets the URL pattern for '売上-input'
        query_params = f'?company={selected_company or ""}&month={selected_month}'
        redirect_url = f'{url}{query_params}'

        if 'tax_calc' in request.POST:
            calc.tax_calc_def(selected_company, selected_month)
            return HttpResponseRedirect(redirect_url)
        
        processed_request = calc.preprocess_post_data(self.request.POST)
        formset = AccountItemFormSet(processed_request)
        
        if formset.is_valid():
            formset.save()
            print("formset was saved")
            return HttpResponseRedirect(redirect_url)
        else:
            print("formerror", formset.errors)
            for i, form in enumerate(formset):
                print(f"Errors in form {i}: {form.errors}")
            return HttpResponseRedirect(redirect_url)

"""
List AccountItem sort by Company & Month
"""
class RevenueListView(LoginRequiredMixin, ListView):
    model = InvoiceCode
    template_name = 'invoice/invoice_list.html'

    def get_context_data(self, **kwargs):
        companies = Company.objects.all()
        company = self.request.GET.get('company')
        month = self.request.GET.get('month') if self.request.GET.get('month') else timezone.now().strftime('%Y-%m-%d')
        _, start_month, eom = strip_date(month)
        invoices = InvoiceCode.objects.filter(
            account_item__invoice_date__gte=start_month, 
            account_item__invoice_date__lte=eom
            ).order_by('-payment_due')
        invoice_data = []


        for invoice in invoices:
            items = AccountItem.objects.filter(company=invoice.account_item.company, invoice_date__gte=start_month, invoice_date__lte=eom).order_by('item_code', '-invoice_date')
            print(f"Filtering Revenue for Invoice ID: {invoice.account_item_slug}, Month: {start_month}")
            print("items", items)
            invoice_data.append({
                'invoice':invoice,
                'items':items
            })
        context = {'forms': invoice_data,'companies':companies,'selected_month':month,'selected_company':company,}
        return context
    
    def post(self, request, *args, **kwargs):
        company = self.request.POST.get('company')  # Use POST instead of GET here
        month = self.request.POST.get('month')  # Use POST instead of GET here
        print("company==>", company)
        print("month==>", month)
        _, start_month, eom = strip_date(month)

        queryset = AccountItem.objects.filter(company=company, invoice_date__gte=start_month, invoice_date__lte=eom).order_by('item_code', '-invoice_date')


        return HttpResponseRedirect(reverse('invoice:invoice-list'))

class PdfCreateDetailView(LoginRequiredMixin, DetailView):
    model = InvoiceCode
    template_name = 'invoice/invoice_detail.html'
    context_object_name = 'contract'

    def get_object(self):
        queryset = AccountItem.objects.all()
        print("kwargs 2001 ====", self.kwargs)
        # Capture the contract_id, selected_bukken, and selected_month from the URL

        if self.kwargs['slug']:
            queryset = queryset.filter(slug=self.kwargs['slug'])

        for invoice in queryset:
            # Access fields of each 請求書 object
            print(f"2001 inside queryset /// 契約書ID: {invoice.slug}, 売上_id: {invoice.id}, 税込売上額: {invoice.invoice_at}")

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # You can also pass the selected_bukken and selected_month if you need them in the template
        context = calc.prepare_invoice_items(self.kwargs)

        return context

    def post(self, request, *args, **kwargs):

        if 'create_pdf' in request.POST:
           
            import ast
            slug = request.POST.get('slug')
            slug = ast.literal_eval(slug)
            kwargs = slug
            # print("kwargs in pdf", slug)
            # return calc.generate_pdf(request, **slug)
            return calc.preview_email_before_send(request, **slug)

def pdfcreate(request, slug):
    slug = {
        'slug':slug,
    }
    return calc.generate_pdf(request, **slug)

class CSVListView(LoginRequiredMixin, ListView):
    template_name = 'invoice/invoice_csv_list.html'
    model = AccountItem

    def get_context_data(self, **kwargs):
        queryset = AccountItem.objects.all() # Article.objects.all() と同じ結果

        orig_start = CsvDate.objects.get(pk=1)
        orig_start = str(orig_start.csvdate)
        orig_end = datetime.today().strftime('%Y-%m-%d')
        # GETリクエストパラメータにkeywordがあれば、それでフィルタする
        start = self.request.GET.get('start')
        if start:
            _, start, _ = strip_date(start)
            end = self.request.GET.get('end')
            _, _, end = strip_date(end)
            queryset = queryset.filter(action_date__gte=start, action_date__lte=end)
            context = {'orig_start':start, 'orig_end':end, 'forms':queryset }
        elif start is None:
            queryset = queryset.filter(action_date__gte=orig_start, action_date__lte=orig_end)
            context = {'orig_start':orig_start, 'orig_end':orig_end, 'forms':queryset }
        return context
    
    def post(self, *args, **kwargs):

        start = self.request.POST.get('start')
        _, start, _ = strip_date(start)
        end = self.request.POST.get('end')
        _, _, end = strip_date(end)
        url = reverse('invoice:csv-create')  # This gets the URL pattern for '売上-input'
        query_params = f'?start={start}&end={end}'
        redirect_url = f'{url}{query_params}'

        queryset = AccountItem.objects.filter(action_date__gte=start, action_date__lte=end)
        st = datetime.strptime(str(start), "%Y-%m-%d")
        ed = datetime.strptime(str(end), "%Y-%m-%d")
        st = st.strftime("%Y%m")
        ed = ed.strftime("%Y%m")
        if queryset.exists():
            calc.export_to_csv(queryset, st, ed)  # Export to CSV
            # No need to redirect before CSV is returned
            orig_start = CsvDate.objects.get(pk=1)
            
            today = datetime.today().strftime('%Y-%m-%d')
            orig_start.csvdate = str(today)
            orig_start.save()
            return calc.export_to_csv(queryset, st, ed)
        
        return HttpResponseRedirect(redirect_url)


"""
CREATE DATABASE BACKUP
"""
def local_db_backup_view(request):
    """Django view to trigger the local database backup."""
    try:
        local_copy_path = backup_logic.copy_local_db()
        filename = os.path.basename(local_copy_path)
        # Success message, maybe include the filename

invoice/templates/invoice/partials/navbar.html
{% load static %}
<nav style="z-index: 200;">
    <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
    <div class="flex items-center justify-between">
      <a href="/" class="flex items-center mr-3">
        <span>
            <img class="w-10 h-10 mr-2" src="{% static 'images/invoice.svg' %}" />
        </span>
        <span class="self-center text-2xl font-semibold whitespace-nowrap">Invoice Manager v1.1.1-pg</span>
      </a>
      {% if user.is_authenticated %}
      
      
      {% endif %}
    </div>
      <button data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center p-2 ml-3 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-default" aria-expanded="false">
        <span class="sr-only">Open main menu</span>
        <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
      </button>
      <div class="hidden w-full md:block md:w-auto" id="navbar-default">
        <ul class="font-medium flex flex-col p-4 md:p-0 my-1 md:my-2 rounded-lg md:flex-row md:space-x-8">
        
        {% if user.is_authenticated %}
        <li>
            <a href="{% url 'invoice:update' %}"
                class="block py-2 pl-3 pr-4 text-white rounded md:p-0" 
                aria-current="page">
                    Update
            </a>
        </li>
        <li>
            <a href="/admin/"
                class="block py-2 pl-3 pr-4 text-white rounded md:p-0" 
                aria-current="page">
                    Admin
            </a>
        </li>
        <li>
            <a href="{% url 'invoice:invoice-list' %}"
                class="block py-2 pl-3 pr-4 text-white rounded md:p-0" 
                aria-current="page">
                List
            </a>
        </li>
        <li>
            <a href="{% url 'invoice:csv-create' %}"
                class="block py-2 pl-3 pr-4 text-white rounded md:p-0" 
                aria-current="page">
                CSV
            </a>
        </li>
        <li>
            <a href="{% url 'invoice:postgres-backup' %}"
                class="block py-2 pl-3 pr-4 text-white rounded md:p-0" 
                aria-current="page">
                BKUP
            </a>
        </li>
        <li>
            <a href="{% url 'invoice:restore-db' %}"
                class="block py-2 pl-3 pr-4 text-white rounded md:p-0" 
                aria-current="page">
                upLoad
            </a>
        </li>
    
            <li>
                <a href="{% url 'invoice:logout_backup' %}" 
                    class="block py-2 pl-3 pr-4 text-white rounded md:p-0" 
                    aria-current="page">
                        Logout
                </a>
            </li>


            {% else %}
            <li>
                <a href="{% url 'account_login' %}" 
                    class="block py-2 pl-3 pr-4 text-white rounded md:p-0" 
                    aria-current="page">
                        Login
                </a>
            </li>
            <li>
                <a href="{% url 'account_reset_password' %}" 
                    class="block py-2 pl-3 pr-4 text-white rounded md:p-0" 
                    aria-current="page">
                        Forgot Password
                </a>
            </li>
        {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  


<!-- <li>
                <a href="{% url 'account_logout' %}" 
                    class="block py-2 pl-3 pr-4 text-white rounded md:p-0" 
                    aria-current="page">
                        Login
                </a>
            </li>
            <li> -->